version: "2.2"

services:
  apache-fpm:
    build: ./apache-fpm
    container_name: "apache-fpm"
    restart: unless-stopped
    volumes:
      - app:/var/www/liveagent
      - /etc/geoip:/opt/geoip
      - /var/run/clamav:/var/run/clamav
    ports:
      - 800:800
    cpus: APACHE_CPU_LIMIT
    mem_limit: APACHE_MEM_LIMIT
    ulimits:
      nproc: 30240
      nofile: 65536
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - "ES_JAVA_OPTS=-XmsMIN_HEAP_SIZE -XmxMAX_HEAP_SIZE"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=true
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    cpus: ELASTIC_CPU_LIMIT
    mem_limit: ELASTIC_MEM_LIMIT
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - IPC_LOCK
  redis:
    build: ./redis
    container_name: "redis"
    restart: unless-stopped
    volumes:
      - redisdata:/var/lib/redis
    ports:
      - 6379:6379
    sysctls:
      - net.core.somaxconn=10000
    cpus: REDIS_CPU_LIMIT
    mem_limit: REDIS_MEM_LIMIT
    ulimits:
      nofile: 90032
  sentinel:
    build: ./redis-sentinel
    container_name: "sentinel"
    restart: unless-stopped
    ports:
      - 26379:26379
    depends_on:
      - redis
    sysctls:
      - net.core.somaxconn=512
volumes:
  app:
    driver: local
  esdata:
    driver: local
  redisdata:
    driver: local
